# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_on_watch_unsub_2b0da2e2ff
ROOST_METHOD_SIG_HASH=_on_watch_unsub_19a0cc98c9


Scenario 1: Test Unsubscribing Points from a Watch
Details:
  TestName: test_unsubscribe_points_from_watch
  Description: The test is envisioned to verify the ability to unsubscribe points from a watch correctly by checking the POST grid operation's response
Execution:
  Arrange: Instantiate a mock haystack session handler object. Prepare a `watch` object and a list of `points` as input parameters. Define a `callback` to process the response.
  Act: Call the `_on_watch_unsub` method with the `watch` and `points` as arguments, along with the `callback`.
  Assert: The expected outcome is a successful post grid operation. The response from the `_post_grid` method will be validated for expected outcomes. 
Validation:
  Rationalize: This is a critical scenario as the ability to unsubscribe 'points' from a 'watch' is a fundamental operation in a haystack session. 

Scenario 2: Test Unsubscribing All Points from a Watch
Details:
  TestName: test_unsubscribe_all_points_from_watch
  Description: The test is envisioned to verify the ability to unsubscribe all points from a watch correctly by checking the POST grid operation's response
Execution:
  Arrange: Instantiate a mock haystack session handler object. Prepare a `watch` object as an input parameter with no `points` data included. Define a `callback` to process the response.
  Act: Call the `_on_watch_unsub` method with the `watch` and `points` as arguments, along with the `callback`.
  Assert: The expected outcome is a successful post grid operation. Also, assert whether the grid's 'close' metadata attribute is set to hszinc.MARKER, considering no specific points were provided for unsubscribing.
Validation:
  Rationalize: This is a critical scenario as the ability to unsubscribe all 'points' from a 'watch' is a fundamental operation in a haystack session. 

Scenario 3: Test Unsubscribing Points with String-Type Watch
Details:
  TestName: test_unsubscribe_points_with_string_type_watch
  Description: This test checks whether the function handles a string type 'watch' correctly. The function should be able to convert a string type 'watch' to its ID.
Execution:
  Arrange: Instantiate a mock haystack session handler object. Prepare a `watch` object as a string and a list of `points` as input parameters. Define a `callback` to process the response.
  Act: Call the `_on_watch_unsub` method with `watch` and `points` as arguments, along with the `callback`.
  Assert: The expected outcome is a successful post grid operation. The response from the `_post_grid` method will be validated for expected outcomes. Also, confirm the 'watch' string is converted to its ID.
Validation:
  Rationalize: This is crucial as the function must properly handle and convert 'watch' objects specified as strings to their corresponding IDs. 

Scenario 4: Invalid type for Watch Object
Details:
  TestName: test_invalid_type_watch_object
  Description: This test checks whether the function handles an invalid type 'watch' input correctly. The function should continue to work by using the ID of the 'watch' directly.
Execution:
  Arrange: Instantiate a mock haystack session handler object. Prepare a `watch` object of an unexpected type and a list of `points` as input parameters. Define a 'callback' to process the response.
  Act: Call the `_on_watch_unsub` method with `watch` and `points` as arguments, along with the `callback`.
  Assert: The expected outcome is a successful post grid operation with the function operating as if the 'watch' was an instance of string_types. Confirm whether the invalid 'watch' type is still treated as a valid ID.
Validation:
  Rationalize: This scenario is key as the function should be robust enough to handle 'watch' objects that are not of the string_type and still operate by using its ID.
"""

# ********RoostGPT********
# Necessary imports
import pytest
from pytest_mock import MockerFixture
from session import HaystackSession
from http.sync import SyncHttpClient
from hszinc import Grid, MODE_ZINC, Ref, MARKER
from six import string_types

class Test_HaystackSessionOnWatchUnsub:
    @pytest.fixture
    def haystack_session(self):
        return HaystackSession(uri="some-uri",
                               api_dir="some-api_dir",
                               grid_format=MODE_ZINC,
                               http_client=SyncHttpClient,
                               http_args=None,
                               tagging_model=None,
                               log=None,
                               pint=False,
                               cache_expiry=3600.0)
    
    @pytest.mark.smoke
    def test_unsubscribe_points_from_watch(self, mocker: MockerFixture, haystack_session):
        # Arrange
        mocker.patch.object(haystack_session, "_post_grid")
        mocker.patch.object(haystack_session, "_obj_to_ref", return_value="Point1")
        watch = mocker.Mock()
        watch.id = "watch_id"
        points = ["Point1", "Point2"]
        callback = "some_cb"
        
        # Act
        haystack_session._on_watch_unsub(watch, points, callback)
        
        # Assert
        haystack_session._post_grid.assert_called_once_with(
            "watchSub", mocker.ANY, callback)
        outbound_grid = haystack_session._post_grid.call_args[0][1]
        assert outbound_grid.metadata["watchId"] == "watch_id"
        assert outbound_grid[0]["id"] == "Point1"

    @pytest.mark.smoke
    def test_unsubscribe_all_points_from_watch(self, mocker: MockerFixture, haystack_session):
        # Arrange 
        mocker.patch.object(haystack_session, "_post_grid")
        watch = mocker.Mock()
        watch.id = "watch_id"
        points = None
        callback = "some_cb"
        
        # Act
        haystack_session._on_watch_unsub(watch, points, callback)
        
        # Assert
        haystack_session._post_grid.assert_called_once_with(
            "watchSub", mocker.ANY, callback)
        outbound_grid = haystack_session._post_grid.call_args[0][1]
        assert outbound_grid.metadata["watchId"] == "watch_id"
        assert outbound_grid.metadata["close"] == MARKER

    @pytest.mark.smoke
    def test_unsubscribe_points_with_string_type_watch(self, mocker: MockerFixture, haystack_session):
        # Arrange
        mocker.patch.object(haystack_session, "_post_grid")
        mocker.patch.object(haystack_session, "_obj_to_ref", return_value="Point1")
        watch = "watch_id"
        points = ["Point1", "Point2"]
        callback = "some_cb"
        
        # Act
        haystack_session._on_watch_unsub(watch, points, callback)
        
        # Assert
        haystack_session._post_grid.assert_called_once_with(
            "watchSub", mocker.ANY, callback)
        outbound_grid = haystack_session._post_grid.call_args[0][1]
        assert outbound_grid.metadata["watchId"] == "watch_id"
        assert outbound_grid[0]["id"] == "Point1"

    def test_invalid_type_watch_object(self, mocker: MockerFixture, haystack_session):
        # Arrange
        mocker.patch.object(haystack_session, "_post_grid")
        mocker.patch.object(haystack_session, "_obj_to_ref", return_value="Point1")
        watch = {"id": "watch_id"}
        points = ["Point1", "Point2"]
        callback = "some_cb"
        
        # Act
        haystack_session._on_watch_unsub(watch, points, callback)
        
        # Assert
        haystack_session._post_grid.assert_called_once_with(
            "watchSub", mocker.ANY, callback)
        outbound_grid = haystack_session._post_grid.call_args[0][1]
        assert outbound_grid.metadata["watchId"] == "watch_id"
        assert outbound_grid[0]["id"] == "Point1"
