# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonsetupTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonsetupTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonsetupTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_on_authenticate_done_3f75a6d6fb
ROOST_METHOD_SIG_HASH=_on_authenticate_done_a0a904fb5d


Scenario 1: Successful Authentication
Details:
  TestName: test_successful_authentication
  Description: This test verifies that the state of the session object is updated correctly when the authentication operation is successful.
Execution:
  Arrange: Initialize an instance of HaystackSession and an instance of NiagaraAXAuthenticateOperation (or Niagara4ScramAuthenticateOperation) with a result that indicates successful authentication (auth in the result tuple is not None).
  Act: Invoke the _on_authenticate_done function with the instance of the operation.
  Assert: Check that the _authenticated attribute in the session instance is True, _client.auth is not None, and _client.cookies is set to the cookies from the result of the operation.
Validation:
  Successful authentication should accurately update session's state. The outcome enforces the integrity of the session state and ensures authenticated operations can proceed as intended.

Scenario 2: Unsuccessful Authentication
Details:
  TestName: test_unsuccessful_authentication
  Description: This test verifies that the state of the session object is updated correctly when the authentication operation fails.
Execution:
  Arrange: Initialize an instance of HaystackSession and an instance of NiagaraAXAuthenticateOperation (or Niagara4ScramAuthenticateOperation) with a result that indicates failed authentication (auth in the result tuple is None).
  Act: Invoke the _on_authenticate_done function with the instance of the operation.
  Assert: Check that the _authenticated attribute in the session instance is False, _client.auth is None, and _client.cookies is None as well.
Validation:
  Failed authentication should correctly update the session state. The outcome guarantees the accuracy and protection of session data, preventing unauthorized operations.

Scenario 3: Error Handling during Authentication 
Details:
  TestName: test_exception_handling_authentication
  Description: This test verifies that the error handling mechanism during the authentication process behaves as expected.
Execution:
  Arrange: Initialize an instance of HaystackSession and an instance of NiagaraAXAuthenticateOperation (or Niagara4ScramAuthenticateOperation). Ensure when accessing its result, an exception is thrown.
  Act: Invoke the _on_authenticate_done function with the operation instance, expecting it to handle the exception.
  Assert: Check that the _authenticated attribute in the session instance is False, _client.auth is None, and _client.cookies is None.
Validation:
  It's essential that application behaves predictably during unexpected events. Thus, appropriately handling exceptions assures program stability and data integrity.

Scenario 4: Final clause execution when Authentication is Completed
Details:
  TestName: test_finalization_authentication
  Description: The test verifies that upon the conclusion of the authentication process, the _auth_op attribute is correctly cleared.
Execution:
  Arrange: Initialize an instance of HaystackSession and an instance of NiagaraAXAuthenticateOperation (or Niagara4ScramAuthenticateOperation). Ensure that _auth_op attribute is set before authentication.
  Act: Invoke the _on_authenticate_done function with the operation instance. 
  Assert: Check that the _auth_op attribute in the session instance is None.
Validation:
  This test ensures that the function cleans after its operation correctly. Clearing _auth_op after authentication terminates may help to avoid unnecessary memory usage or potential confusion caused by stale data.
"""

# ********RoostGPT********
import pytest
from pyhaystack.session import HaystackSession
from pyhaystack.ops.vendor.niagara import NiagaraAXAuthenticateOperation
from pyhaystack.ops.vendor.niagara_scram import Niagara4ScramAuthenticateOperation
from unittest.mock import Mock
from pyhaystack.client.niagara import NiagaraHaystackSession

class Test_NiagaraHaystackSessionOnAuthenticateDone:

    @pytest.mark.auth
    def test_successful_authentication(self):
        test_session = HaystackSession('http://example.com', 'user', 'pass')
        operation = NiagaraAXAuthenticateOperation(test_session)
        operation.result = ('auth-result', 'cookies-result')
        test_session._on_authenticate_done(operation)
        assert test_session._authenticated == True
        assert test_session._client.auth != None
        assert test_session._client.cookies == 'cookies-result'

    @pytest.mark.auth
    def test_unsuccessful_authentication(self):
        test_session = HaystackSession('http://example.com', 'user', 'pass')
        operation = NiagaraAXAuthenticateOperation(test_session)
        operation.result = (None, 'cookies-result')
        test_session._on_authenticate_done(operation)
        assert test_session._authenticated == False
        assert test_session._client.auth == None
        assert test_session._client.cookies == None

    @pytest.mark.auth
    @pytest.mark.exception
    def test_exception_handling_authentication(self):
        test_session = HaystackSession('http://example.com', 'user', 'pass')
        operation = NiagaraAXAuthenticateOperation(test_session)
        operation.result = Mock(side_effect=Exception('Error during authentication'))
        with pytest.raises(Exception):
            test_session._on_authenticate_done(operation)
        assert test_session._authenticated == False
        assert test_session._client.auth == None
        assert test_session._client.cookies == None

    @pytest.mark.auth
    def test_finalization_authentication(self):
        test_session = HaystackSession('http://example.com', 'user', 'pass')
        operation = NiagaraAXAuthenticateOperation(test_session)
        operation.result = ('auth-result', 'cookies-result')
        test_session._auth_op = operation
        test_session._on_authenticate_done(operation)
        assert test_session._auth_op == None
