# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=his_write_series_1599177fc6
ROOST_METHOD_SIG_HASH=his_write_series_8f9d386b28


Scenario 1: Check successful write of historical data
Details:
  TestName: test_successful_historical_write
  Description: The test is intended to verify if the historical data is written successfully when a valid point, a valid series, and a valid optional timezone are provided as input. A callback function should also respond as expected after a successful operation.
Execution:
  Arrange: Initialize a 'point' entity, 'series' data, and a valid timezone 'tz'. Prepare a callback function to connect to operations.
  Act: Invoke his_write_series with the prepared inputs.
  Assert: The operation performed should be successful without any exceptions, and the callback function should be invoked and work as expected after the operation.
Validation:
  Rationalize: This test is important to ensure that the function works as expected under normal operations, successfully writing historical data and interacting as expected with the callback function if provided one.

Scenario 2: Check functionality without callback
Details:
  TestName: test_functionality_without_callback
  Description: The test is intended to verify if the historical data is written successfully when an optional callback isn't provided as an argument.
Execution:
  Arrange: Initialize a 'point' entity, 'series' data, and a valid timezone 'tz'.
  Act: Invoke his_write_series with the created inputs but no callback.
  Assert: The operation performed should be successful without invoking any callback function.
Validation:
  Rationalize: This test is important to ensure the function can handle situations where no callback function is provided.

Scenario 3: Check execution with invalid point entity
Details:
  TestName: test_execution_with_invalid_point_entity
  Description: The test is intended to check how the function behaves when it receives an invalid point entity as input.
Execution:
  Arrange: Prepare an invalid 'point' entity.
  Act: Invoke his_write_series providing the invalid 'point' entity and observe the function's behavior.
  Assert: The function should handle the invalid 'point' entity appropriately, most likely throwing an exception demonstrating that it cannot operate on an invalid input.
Validation:
  Rationalize: This test is crucial to ensuring the function is robust and can deal with incorrect inputs appropriately.

Scenario 4: Check effects of different timezone inputs
Details:
  TestName: test_different_timezone_inputs
  Description: This test aims to investigate how different timezones inputs to the function affect the writing of historical data.
Execution:
  Arrange: Initialize a 'point' entity and 'series' data.
  Act: Invoke his_write_series with different, valid timezone arguments and observe the resulting differences in the written historical data.
  Assert: The timestamps in the written historical data should accurately represent the provided timezone.
Validation:
  Rationalize: This test is important for verifying how the function handles timezone translation and to ensure the accuracy of written historical data.
"""

# ********RoostGPT********
# Necessary imports
import pytest
from session import HaystackSession
from pytest import raises
from ops import ops as his_ops

# Test Class
class Test_HaystackSessionHisWriteSeries:
    # Mock data
    point = 'AirTemp'
    series = {'12/08/2021 14:00':22.4, '12/08/2021 15:00':23.1}
    tz = 'Asia/Kolkata'
    callback = lambda op: op.go()
 
    @pytest.mark.regression
    def test_successful_historical_write(self):
        # Arrange
        hs = HaystackSession('https://www.testserver.com', 'haystack')
        hs._HIS_WRITE_SERIES_OPERATION = lambda self, point, series, tz: his_ops(self.write_series, point, series, tz)

        # Act
        op = hs.his_write_series(self.point, self.series, tz=self.tz, callback=self.callback)

        # Assert
        assert op
        assert his_ops.isconnected == True

    @pytest.mark.regression
    def test_functionality_without_callback(self):
        # Arrange
        hs = HaystackSession('https://www.testserver.com', 'haystack')
        hs._HIS_WRITE_SERIES_OPERATION = lambda self, point, series, tz: his_ops(self.write_series, point, series, tz)

        # Act
        op = hs.his_write_series(self.point, self.series, tz=self.tz)

        # Assert
        assert op
        assert his_ops.isconnected == False

    @pytest.mark.regression
    def test_execution_with_invalid_point_entity(self):
        # Arrange
        invalid_point = 123
        hs = HaystackSession('https://www.testserver.com', 'haystack')
        hs._HIS_WRITE_SERIES_OPERATION = lambda self, point, series, tz: his_ops(self.write_series, point, series, tz)

        # Act & Assert
        with raises(Exception):
            hs.his_write_series(invalid_point, self.series, tz=self.tz)

    @pytest.mark.regression
    def test_different_timezone_inputs(self):
        # Arrange
        tz = 'America/New_York'
        hs = HaystackSession('https://www.testserver.com', 'haystack')
        hs._HIS_WRITE_SERIES_OPERATION = lambda self, point, series, tz: his_ops(self.write_series, point, series, tz)

        # Act 
        op = hs.his_write_series(self.point, self.series, tz=tz)
        
        # Assert 
        assert op
        # TODO: Add logic/code to verify that the written timestamps in the data have been translated into the supplied timezone
