# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_on_his_read_b0c7a06a5e
ROOST_METHOD_SIG_HASH=_on_his_read_f348a70f8c


Scenario 1: Check with Slice Range
Details:
  TestName: test_slice_range
  Description: An explanation of what the test is intended to verify, focusing on a specific aspect of the business logic of `_on_his_read`.
Execution:
  Arrange: Create a range object in Python using the slice functionality, such as `rng=slice(1,10,1)`. Provide a valid point object and a callback function.
  Act: Call the function `_on_his_read` with a slice range.
  Assert: Verify the conversion of the slice range into a comma-separated string and if it matches its respective string got through `hszinc.dump_scalar`.
Validation:
  Rationalize: This scenario is aimed to test the function's ability to correctly handle slice range.

Scenario 2: Check with a non-string and non-slice range
Details:
  TestName: test_scalar_range
  Description: An explanation of what the test is intended to verify, focusing on a specific aspect of the business logic of `_on_his_read`.
Execution:
  Arrange: Create a range object not being a slice object or string such as an integer or floating point number. Provide a valid point object and a callback function.
  Act: Call the function `_on_his_read` with a non-slice non-string range.
  Assert: According to the business logic, for non-string types and non-slice range, it is expected that the `hszinc.dump_scalar` is called on the `rng` and its result is as expected.
Validation:
  Rationalize: This scenario is important to check the function's ability to handle ranges which are neither string types nor slice.

Scenario 3: Test with a string type range
Details:
  TestName: test_string_range
  Description: An explanation of what the test is intended to verify, focusing on a specific aspect of the business logic of `_on_his_read`.
Execution:
  Arrange: Create a range object as a string type. Provide a valid point object and a callback function.
  Act: Call the function `_on_his_read` with the string range.
  Assert: According to the business logic, for string types, it is expected that the `hszinc.dump_scalar` is called on the `rng` with `hszinc.MODE_ZINC` mode and its result matches as expected.
Validation:
  Rationalize: This scenario is important as it checks the correct operation of the function when provided with a string type as range.

Scenario 4: Test with improper range type
Details:
  TestName: test_improper_range_type
  Description: An explanation of what the test is intended to verify, focusing on a specific aspect of the business logic of `_on_his_read`.
Execution:
  Arrange: Create a range object with a non-expected type such as complex. Provide a valid point object and a callback function.
  Act: Call the function `_on_his_read` with the non-expected range type.
  Assert: As this is out of the business logic of the function, we might expect it to throw an error, or unexpected behaviour.
Validation:
  Rationalize: This scenario is important to check the robustness of the function when provided with improper inputs.

Scenario 5: Test with None in Slice
Details:
  TestName: test_none_in_slice_range
  Description: An explanation of what the test is intended to verify, focusing on the business logic of `_on_his_read`.
Execution:
  Arrange: Create a slice with None such as `rng=slice(None)`. Provide a valid point object and a callback function.
  Act: Call the function `_on_his_read` with a range having None.
  Assert: According to the logic of the function, `hszinc.dump_scalar` is called on individual elements of the range slice. As None object does not throw an error in `hszinc.dump_scalar`, hence it will not result in an error but the output needs to be validated whether it matches our expectation or not.
Validation:
  Rationalize: This scenario is important to check the correct operation of the function when provided with a slice object containing None in slice.

"""

# ********RoostGPT********
# Necessary imports
import pytest
# Import for the function/method to be tested (e.g., from calc import division)
from session import HaystackSession
import hszinc
from six import string_types
from unittest.mock import MagicMock

class Test_HaystackSessionOnHisRead:

    @pytest.mark.valid
    def test_slice_range(self):
        # Arrange
        session = HaystackSession('http://test.site', '/api')
        session._get_grid = MagicMock()
        point = 'test_point'
        callback = lambda x: x
        rng = slice(1,8,2)

        # Act
        session._on_his_read(point, rng, callback)
        expected_range = ','.join([hszinc.dump_scalar(p) for p in (rng.start, rng.stop)])

        # Assert
        session._get_grid.assert_called_with("hisRead", callback, args={"id": session._obj_to_ref(point), "range": expected_range})

    @pytest.mark.valid
    def test_scalar_range(self):
        # Arrange
        session = HaystackSession('http://test.site', '/api')
        session._get_grid = MagicMock()
        point = 'test_point'
        callback = lambda x: x
        rng = 100

        # Act
        session._on_his_read(point, rng, callback)
        expected_range = hszinc.dump_scalar(rng)

        # Assert
        session._get_grid.assert_called_with("hisRead", callback, args={"id": session._obj_to_ref(point), "range": expected_range})
        
    @pytest.mark.valid
    def test_string_range(self):
        # Arrange
        session = HaystackSession('http://test.site', '/api')
        session._get_grid = MagicMock()
        point = 'test_point'
        callback = lambda x: x
        rng = '100'

        # Act
        session._on_his_read(point, rng, callback)
        expected_range = hszinc.dump_scalar(rng, mode=hszinc.MODE_ZINC)

        # Assert
        session._get_grid.assert_called_with("hisRead", callback, args={"id": session._obj_to_ref(point), "range": expected_range})

    @pytest.mark.invalid
    def test_improper_range_type(self):
        # Arrange
        session = HaystackSession('http://test.site', '/api')
        session._get_grid = MagicMock()
        point = 'test_point'
        callback = lambda x: x
        rng = 1 + 1j

        # Act & Assert
        with pytest.raises(Exception):
            session._on_his_read(point, rng, callback)

    @pytest.mark.valid
    def test_none_in_slice_range(self):
        # Arrange
        session = HaystackSession('http://test.site', '/api')
        session._get_grid = MagicMock()
        point = 'test_point'
        callback = lambda x: x
        rng = slice(None)

        # Act
        session._on_his_read(point, rng, callback)
        expected_range = ','.join([hszinc.dump_scalar(p) for p in (rng.start, rng.stop)])

        # Assert
        session._get_grid.assert_called_with("hisRead", callback, args={"id": session._obj_to_ref(point), "range": expected_range})
