# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___9aa63849ca
ROOST_METHOD_SIG_HASH=__init___6bad58e5c6


Scenario 1: Successful initialization of Niagara4HaystackSession with valid parameters
Details:
  TestName: test_init_niagara4haystacksession
  Description: This test is meant to verify if the session handler is successfully initialized when valid parameters are passed. 
Execution:
  Arrange: Instantiate Niagara4HaystackSession by providing valid values for uri, username, password, and grid_format.
  Act: The __init__ function will be invoked with parameters passed during object construction.
  Assert: Confirm that the properties _username, _password, _authenticated and _uri of the session object have been properly initialized. Also, check the type of session object to Niagara4HaystackSession.
Validation:
  This Test ascertains the function's core ability to set up a proper session connection when provided with appropriate parameters.

Scenario 2: Initializing Niagara4HaystackSession with custom grid format
Details:
  TestName: test_init_grid_format
  Description: The test is meant to verify if the session handler supports the use of a custom grid format during initialization.
Execution:
  Arrange: Instantiate Niagara4HaystackSession by providing valid values for uri, username, password, and a custom value for grid_format(not default)
  Act: The __init__ method is invoked with arguments provided during instantiation.
  Assert: Confirm that the appropriately defined grid format is assigned to the session handler.
Validation:
  This test ensures the function's flexibility in working with custom grid formats apart from the default json format.

Scenario 3: Verifying the default state of authentication status
Details:
  TestName: test_auth_status_post_initialization
  Description: This test is intended to validate that the initial state of _authenticated property of the session handler object is False post initialization.
Execution:
  Arrange: Instantiate Niagara4HaystackSession with valid values for uri, username, and password.
  Act: The __init__ function will be invoked during object creation.
  Assert: Check that the _authenticated property of the session object is False.
Validation:
  This test ensures that the session handler initiates with the correct authentication status as per the business rules.

Scenario 4: Check if the same URI is assigned to both the session handler and super class
Details:
  TestName: test_super_class_uri_assignment
  Description: This test verifies if the uri passed during the session handler's construction is assigned to its superclass.
Execution:
  Arrange: Instantiate a Niagara4HaystackSession with a valid uri, username, and password.
  Act: The __init__ method is called upon object creation.
  Assert: Assert that the superclass's uri from which Niagara4HaystackSession inherits, has the same uri as would be assigned to the session handler object.
Validation:
  This test provides confidence that the URI is correctly propagated to the parent class allowing for correct interaction with the Haystack installation.
"""

# ********RoostGPT********
import pytest
from niagara import Niagara4HaystackSession
import hszinc

class Test_Niagara4HaystackSessionInit:
    @pytest.mark.smoke
    def test_init_niagara4haystacksession(self):
        test_session = Niagara4HaystackSession(uri='http://localhost:8000', username='test', password='password')
        assert test_session._username == 'test'
        assert test_session._password == 'password'
        assert test_session._authenticated == False
        assert test_session._uri == 'http://localhost:8000'
        assert isinstance(test_session, Niagara4HaystackSession)

    @pytest.mark.valid
    def test_init_grid_format(self):
        test_session = Niagara4HaystackSession(uri='http://localhost:8000', username='test', password='password', grid_format=hszinc.MODE_ZINC)
        assert test_session._grid_format == hszinc.MODE_ZINC

    @pytest.mark.regression
    def test_auth_status_post_initialization(self):
        test_session = Niagara4HaystackSession(uri='http://localhost:8000', username='test', password='password')
        assert test_session._authenticated == False

    @pytest.mark.valid
    def test_super_class_uri_assignment(self):
        # Assuming HaystackSession is the parent class
        from session import HaystackSession

        test_uri = 'http://localhost:8000'

        test_session = Niagara4HaystackSession(uri=test_uri, username='test', password='password')

        assert issubclass(Niagara4HaystackSession, HaystackSession)
        assert test_session._uri == test_uri == HaystackSession._uri
