# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_on_his_write_544a8aac31
ROOST_METHOD_SIG_HASH=_on_his_write_1545ada6df


**Scenario 1:** Validate if `timestamp_records` with a `to_dict` attribute converts the data to dictionary format and sorts the timestamp correctly to maintain the order.
Details:
  TestName: test_timestamp_record_conversion_and_order
  Description: This test will ensure that the `timestamp_records` data is converted into dictionary format if it has a `to_dict` attribute and it's sorted correctly in ascending order by timestamp.
Execution:
  Arrange: Initialize an object of the class containing `_on_his_write` method, prepare some mock `timestamp_records` with `to_dict` attribute, along with other required arguments for irs invocation.
  Act: Invoke the `_on_his_write` method of the initialized object created in Arrange, with representative `timestamp_records` and other inputs.
  Assert: Check if the `timestamp_records` has been correctly converted to dictionary and sorted in ascending order by the timestamp.
Validation:
  Rationalize: The test is important as it validates the successful transformation of data to meet the input format used in the method `_on_his_write` and highlights an integral part of the function's business logic.

**Scenario 2:** Evaluate if the grid metadata `"id"` gets populated with the result of the `_obj_to_ref(point)` function.
Details:
  TestName: test_grid_metadata_id_populate
  Description: This test will confirm that the`grid.metadata["id"]` is populated correctly with the return value of `_obj_to_ref(point)` function.
Execution:
  Arrange: Initialize an object of the class containing `_on_his_write`, prepare a point and mock `timestamp_records` required for its invocation.
  Act: Invoke the `_on_his_write` method of the initialized object created in Arrange, with representative point and other inputs.
  Assert: Confirm that the `grid.metadata["id"]` has been populated correctly with the output of  `_obj_to_ref(point)`.
Validation:
  Rationalize: This test scenario is crucial, as it assures the function's capability to set grid metadata correctly which is necessary to maintain the correct mapping and reference to the data.

**Scenario 3:** Confirm correct functionality of `_post_grid`.
Details:
  TestName: test_post_grid_invocation
  Description: This scenario will ensure that the `_post_grid` function is correctly invoked with the correct URI, grid, and callback, among other arguments.
Execution:
  Arrange: Initialize an object of the class containing `_on_his_write`, prepare a point and mock `timestamp_records` required for its invocation.
  Act: Invoke `_on_his_write` with representative inputs, thus resulting in the invocation of `_post_grid`.
  Assert: Verify that `_post_grid` was triggered with the correct arguments and confirm that the expected return value from `_post_grid` matches the outcome.
Validation:
  Rationalize: This scenario validates the function's competence to correctly trigger HTTP POST requests, which is a vital aspect of `_on_his_write`'s functionality.

**Scenario 4:** Test for unrecognized `post_format`.
Details:
  TestName: test_unrecognized_post_format
  Description: This scenario will test how the function `_on_his_write` behaves when provided an unrecognized `post_format`.
Execution:
  Arrange: Initialize the object of the class containing `_on_his_write`, prepare point and mock `timestamp_records` required for its invocation.
  Act: Invoke `_on_his_write` with the prepared inputs and provide an unrecognized `post_format`.
  Assert: Check for an exception being thrown indicating unrecognized `post_format`.
Validation:
  Rationalize: This test validates the function's tolerance to incorrect `post_format`, which ensures the stability and robustness of `_on_his_write`.
"""

# ********RoostGPT********
# Necessary imports
import pytest
from unittest.mock import Mock, call
import hszinc
from session import HaystackSession

class Test_HaystackSessionOnHisWrite:
    @pytest.mark.smoke
    def test_timestamp_record_conversion_and_order(self):
        # Arrange
        session = HaystackSession(uri='', api_dir='')
        point = 'point'
        timestamp_records = Mock()
        timestamp_records.to_dict.return_value = {2: 'b', 1: 'a'}
        callback = Mock()

        # Act
        session._on_his_write(point, timestamp_records, callback)

        # Assert
        timestamp_records.to_dict.assert_called_once_with()   # to_dict called on timestamp_records
        callback.assert_has_calls([call({"ts": 1, "val": "a"}), call({"ts": 2, "val": "b"})])  # Callback called with sorted records

    @pytest.mark.smoke
    def test_grid_metadata_id_populate(self):
        # Arrange
        session = HaystackSession(uri='', api_dir='')
        point = 'point'
        timestamp_records = {}
        callback = Mock()

        # Act
        session._on_his_write(point, timestamp_records, callback)

        # Assert
        assert session._grid.metadata['id'] == session._obj_to_ref(point)

    @pytest.mark.smoke
    def test_post_grid_invocation(self):
        # Arrange
        session = HaystackSession(uri='', api_dir='')
        point = 'point'
        timestamp_records = {1: 'a', 2: 'b'}
        callback = Mock()

        # Mock internal _post_grid method
        post_grid_mock = Mock()
        session._post_grid = post_grid_mock

        # Act
        session._on_his_write(point, timestamp_records, callback)

        # Assert
        post_grid_mock.assert_called_once_with('hisWrite', session._grid, callback, post_format=hszinc.MODE_ZINC)

    @pytest.mark.negative
    def test_unrecognized_post_format(self):
        # Arrange
        session = HaystackSession(uri='', api_dir='')
        point = 'point'
        timestamp_records = {1: 'a', 2: 'b'}
        callback = Mock()
        unrecognized_post_format = 'unrecognized'

        # Act & Assert
        with pytest.raises(ValueError) as e:
            session._on_his_write(point, timestamp_records, callback, post_format=unrecognized_post_format)
        assert str(e.value) == 'Unrecognised post format %s' % unrecognized_post_format
