# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=logout_f1ad123d15
ROOST_METHOD_SIG_HASH=logout_fc813b5064


Scenario 1: Test for successful logout
Details:
  TestName: test_successful_logout
  Description: This test is intended to verify if the function correctly logs out when the status code is 200.
Execution:
  Arrange: An instance of the NiagaraHaystackSession class is initialized with appropriate parameters. The session user is successfully logged in.
  Act: The logout method is invoked on the session instance.
  Assert: The log message "You've been properly disconnected" is expected.
Validation:
  This is important to verify the function's ability to handle successful logout.

Scenario 2: Test for unsuccessful logout
Details:
  TestName: test_unsuccessful_logout
  Description: This test is intended to verify if the function correctly handles the unsuccessful logout case when the status code is not 200.
Execution:
  Arrange: An instance of the NiagaraHaystackSession class is initialized with appropriate parameters. The session user is successfully logged in.
  Act: The logout method is invoked on the session instance.
  Assert: The log message "Failed to close nhaystack session" is expected.
Validation:
  This test ensures that the logout method reacts properly to an unsuccessful attempt of logout.

Scenario 3: Test for unexpected status code attribute error
Details:
  TestName: test_unexpected_attribute_error
  Description: This test is meant to check if the function properly handles an "AttributeError" during the log out process dealing with the absence of status code.
Execution:
  Arrange: Initialize an instance of the NiagaraHaystackSession class with suitable parameters. The session user is successfully logged in.
  Act: Call the logout method on the session instance.
  Assert: The log message "Failed to close nhaystack session" is expected.
Validation:
  This test is crucial in ensuring the logout method can gracefully handle unexpected "AttributeError" and notify the user properly.

  
Scenario 4: Test for logout without prior login
Details:
  TestName: test_logout_without_login
  Description: This test is intended to confirm if the logout function handles cases where a user tries to logout without having logged in first.
Execution:
  Arrange: An instance of the NiagaraHaystackSession class is initialized with appropriate parameters. The user is not logged in to the session.
  Act: The logout method is invoked on the session instance.
  Assert: The log message "Failed to close nhaystack session" is expected.
Validation:
  This test highlights the logout method's robustness in handling cases where users attempt to log out without a prior login.
"""

# ********RoostGPT********
import pytest
import logging
from session import HaystackSession
from ops.vendor.niagara import NiagaraAXAuthenticateOperation
from ops.vendor.niagara_scram import Niagara4ScramAuthenticateOperation
from mixins.vendor.niagara.bql import BQLOperation, BQLMixin
from mixins.vendor.niagara.encoding import EncodingMixin
from unittest.mock import Mock, patch
import hszinc
from niagara import NiagaraHaystackSession

class Test_NiagaraHaystackSessionLogout:

	@patch.object(NiagaraHaystackSession, '_get')
	@patch.object(logging, 'info')
	def test_successful_logout(self, mock_log_info, mock_get):
	    session = NiagaraHaystackSession("TestURI", "TestUser", "testPassword")
	    mock_get.side_effect = lambda x, y, z: y(Mock(status_code=200))
	    session.logout()
	    mock_log_info.assert_called_once_with("You've been properly disconnected")

	@patch.object(NiagaraHaystackSession, '_get')
	@patch.object(logging, 'warning')
	def test_unsuccessful_logout(self, mock_log_warning, mock_get):
	    session = NiagaraHaystackSession("TestURI", "TestUser", "testPassword")
	    mock_get.side_effect = lambda x, y, z: y(Mock(status_code=400))
	    session.logout()
	    mock_log_warning.assert_called_with("Failed to close nhaystack session")

	@patch.object(NiagaraHaystackSession, '_get')
	@patch.object(logging, 'warning')
	def test_unexpected_attribute_error(self, mock_log_warning, mock_get):
	    session = NiagaraHaystackSession("TestURI", "TestUser", "testPassword")
	    mock_get.side_effect = lambda x, y, z: y(Mock(status_code=None))
	    session.logout()
	    mock_log_warning.assert_called_with("Failed to close nhaystack session")

	@patch.object(NiagaraHaystackSession, '_get')
	@patch.object(logging, 'warning')
	def test_logout_without_login(self, mock_log_warning, mock_get):
	    session = NiagaraHaystackSession("TestURI", "TestUser", "testPassword")
	    session._authenticated = False
	    session.logout()
	    mock_get.assert_not_called()
	    mock_log_warning.assert_called_with("Failed to close nhaystack session")
