# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=his_write_series_1599177fc6
ROOST_METHOD_SIG_HASH=his_write_series_8f9d386b28


Scenario 1: Successful writing of historical series data
Details:
  TestName: test_his_write_series_success
  Description: This test is intended to verify if the 'his_write_series' function can successfully write the historical data of a given point.
Execution:
  Arrange: We setup the point and series objects with valid data and prepare a mock client to ensure write operations.
  Act: The 'his_write_series' function is called with the point, series and mock client objects as arguments.
  Assert: It will be checked whether if the return object is an operation object and if there were no exceptions during the process.
Validation:
  A successful test here shows that the function can write series correctly to a given point in the system. It validates the principal business requirement of the method which is writing historical data series.

Scenario 2: Function handling of callback
Details:
  TestName: test_his_write_series_with_callback
  Description: This test verifies if the 'his_write_series' function can handle callback functions correctly.
Execution:
  Arrange: Setup valid point and series objects and a mock callback function.
  Act: The 'his_write_series' function is invoked with point, series, and the mock callback as parameters.
  Assert: It is asserted that the callback function has been called after the operation.
Validation:
  This scenario is important as callbacks are an essential part of asynchronous programming in Python. If callbacks are handled correctly it ensures that subsequent logic can be correctly executed after a series has been written.

Scenario 3: Timezone handling while writing series
Details:
  TestName: test_his_write_series_with_timezone
  Description: This test is built to check if timezone is correctly applied when writing historical series.
Execution:
  Arrange: Setup valid point and series objects along with a timezone.
  Act: Invoke 'his_write_series' function with valid point, series and a timezone as parameters.
  Assert: Confirm that the time values written in the series comply with the used timezone.
Validation:
  This test is vital to ensure the correctness of datetime data in the written series. Incorrect timezone handling could lead to false interpretations of the historical data.

Scenario 4: Error handling with invalid series data
Details:
  TestName: test_his_write_series_with_invalid_series
  Description: This test is built to check how the function handles invalid(having missing data or nonsensical information) series data.
Execution:
  Arrange: Setup valid point object and a series with invalid data.
  Act: Call 'his_write_series' function with valid point and invalid series data.
  Assert: It is expected that an error should be raised due to invalid series data.
Validation:
  This test is significant in understanding the robustness of the system. It showcases if the function can handle erroneous scenario gracefully while maintaining the integrity of the system.
"""

# ********RoostGPT********
import pytest
from unittest.mock import Mock, call
from session import HaystackSession
from ops.ops import Operation
import pytz

class Test_HaystackSessionHisWriteSeries:

    def test_his_write_series_success(self):
        mock_client = Mock()
        point = {"id": "point1"}
        series = {"time": ["2020-01-01 00:00:00", "2020-01-02 00:00:00"], "value": [10, 20]}
        assert isinstance(HaystackSession.his_write_series(self, point, series, tz=None, callback=None, client=mock_client), Operation)

    def test_his_write_series_with_callback(self):
        mock_callback = Mock()
        mock_client = Mock()
        point = {"id": "point2"}
        series = {"time": ["2020-01-01 00:00:00", "2020-01-02 00:00:00"], "value": [10, 20]}
        HaystackSession.his_write_series(self, point, series, tz=None, callback=mock_callback, client=mock_client)
        mock_callback.assert_called_once()

    def test_his_write_series_with_timezone(self):
        mock_client = Mock()
        point = {"id": "point3"}
        series = {"time": ["2020-01-01 00:00:00", "2020-01-02 00:00:00"], "value": [10, 20]}
        timezone = pytz.timezone('America/New_York')
        result = HaystackSession.his_write_series(self, point, series, tz=timezone, callback=None, client=mock_client)
        assert isinstance(result, Operation)
        assert result.tz == timezone

    def test_his_write_series_with_invalid_series(self):
        mock_client = Mock()
        point = {"id": "point4"}
        series = {"time": ["2020-01-01 00:00:00"], "value": [10, 20]}  # mismatch in time and value length
        with pytest.raises(Exception):
            HaystackSession.his_write_series(self, point, series, tz=None, callback=None, client=mock_client)
