# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___a7230524d1
ROOST_METHOD_SIG_HASH=__init___2a102b4e16


Scenario 1: Verifying correct initialization with all arguments provided
Details:
  TestName: test_init_with_all_arguments
  Description: The test will verify if the function "__init__" correctly initializes all attributes when all right arguments are passed.
Execution:
  Arrange: Create proper variables to simulate the provided arguments, like uri, api_dir, http_client, tagging_model, log etc.
  Act: Call the "__init__" method with appropriate values for required parameters and observe the method's behavior.
  Assert: Check if all attributes are correctly initialized like _log, _grid_format, _client, _api_dir etc.
Validation:
  Rationalize: The "__init__" function must correctly initialize all attributes when all correct arguments are passed. Ensuring it functions correctly provides assurance that the class instance has been properly instantiated.

Scenario 2: Verify if correct log instance is created when log argument is None
Details:
  TestName: test_init_with_log_none
  Description: The test will verify if the function "__init__" correctly initializes the "_log" attribute, when log argument is None.
Execution:
  Arrange: Provide None for `log` along with other necessary constructors.
  Act: Invoke the "__init__" with `log` as None and observe the object as it is created.
  Assert: Check if "_log" attribute is initialized with an instance of "logging.getLogger".
Validation:
  Rationalize: A proper logging instance must be created when log is not provided to aid in debugging and tracking performance of the application. If log is provided, this instance should be used instead.

Scenario 3: Verify configuration of hszinc to use Pint or basic quantity as per `pint` argument
Details:
  TestName: test_hszinc_configuration_with_pint
  Description: Verify that the hszinc quantity mode is correctly set given the `pint` argument.
Execution:
  Arrange: Create constructor variables such as uri, api_dir, http_client, tagging_model, log, etc.
  Act: Invoke the "__init__" with both `pint` as True and False and observe the `_use_pint` attribute.
  Assert: Check whether `_use_pint` is True or False, as per the `pint` argument given.
Validation:
  Rationalize: The hszinc library should be correctly configured for quantities as per the boolean `pint` argument. This check will ensure the rest of the application functions as expected.

Scenario 4: Verify correct initialization of `tagging_model` attribute
Details:
  TestName: test_tagging_model_initialization
  Description: This test will verify if the "_tagging_model" attribute is correctly initialized with the given tagging_model argument.
Execution:
  Arrange: Create necessary variables for the constructor including a representative TaggingModel instance.
  Act: Call "__init__" method with necessary parameters including the TaggingModel constructed.
  Assert: Check if "_tagging_model" is initialized with the instance of TaggingModel passed.
Validation:
  Rationalize: The "_tagging_model" attribute should be properly initialized with the given tagging_model, as it could affect further module functionalities.

Scenario 5: Testing the error thrown when an unrecognised grid format is used
Details:
  TestName: test_unrecognized_grid_format
  Description: This test is designed to verify if the function "__init__" accurately throws an exception when an unrecognized grid format is passed.
Execution:
  Arrange: Initialize variables required for the constructor. The `grid_format` should be an unrecognized format.
  Act: Invoke the "__init__" method using the variables from the "Arrange" phase.
  Assert: Expect a ValueError indicating an unrecognised grid format.
Validation:
  Rationalize: Ensuring that the "__init__" function correctly throws an error for unrecognized grid formats ensures the application behaves predictably and avoids potential runtime issues later.

"""

# ********RoostGPT********
import pytest
import logging
import hszinc
import weakref
from threading import Lock
import sync
from entity.models.haystack import HaystackTaggingModel
from session import HaystackSession

class Test_HaystackSessionInit:

    @pytest.mark.smoke
    def test_init_with_all_arguments(self):
        # Arrange
        uri = "http://example.com"
        api_dir = "/api"
        grid_format = hszinc.MODE_ZINC
        http_client = sync.SyncHttpClient
        http_args = {"debug":True}
        tagging_model = HaystackTaggingModel
        log = logging.getLogger("Test")
        pint = True
        cache_expiry = 3600.0
        # Act
        haystack_session = HaystackSession(uri, api_dir, grid_format, http_client, http_args, tagging_model, log, pint, cache_expiry)
        # Assert
        assert haystack_session._log == log
        assert haystack_session._grid_format == grid_format
        assert isinstance(haystack_session._client, sync.SyncHttpClient)
        assert haystack_session._api_dir == api_dir
        assert isinstance(haystack_session._entities, weakref.WeakValueDictionary)
        assert isinstance(haystack_session._tagging_model, HaystackTaggingModel)
        assert haystack_session._grid_expiry == cache_expiry
        assert isinstance(haystack_session._grid_cache, dict)

    @pytest.mark.smoke
    def test_init_with_log_none(self):
        # Arrange
        uri = "http://example.com"
        api_dir = "/api"
        # Act
        haystack_session = HaystackSession(uri, api_dir)
        # Assert
        assert isinstance(haystack_session._log, logging.Logger)

    @pytest.mark.valid
    def test_hszinc_configuration_with_pint(self):
        # Arrange
        uri = "http://example.com"
        api_dir = "/api"
        pint = True
        # Act
        haystack_session = HaystackSession(uri, api_dir, pint=pint)
        # Assert
        assert haystack_session._use_pint == pint

    @pytest.mark.valid
    def test_tagging_model_initialization(self):
        # Arrange
        uri = "http://example.com"
        api_dir = "/api"
        tagging_model = HaystackTaggingModel
        # Act
        haystack_session = HaystackSession(uri, api_dir, tagging_model=tagging_model)
        # Assert
        assert isinstance(haystack_session._tagging_model, HaystackTaggingModel)

    @pytest.mark.exception
    def test_unrecognized_grid_format(self):
        # Arrange
        uri = "http://example.com"
        api_dir = "/api"
        grid_format = "INVALID_FORMAT"
        # Act & Assert
        with pytest.raises(ValueError):
            HaystackSession(uri, api_dir, grid_format=grid_format)
