# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_on_watch_sub_8c8bd89c83
ROOST_METHOD_SIG_HASH=_on_watch_sub_ab3e27c935


Scenario 1: Verify `_on_watch_sub` handles points correctly
Details:
  TestName: test_watch_sub_valid_points
  Description: Validate how the function `_on_watch_sub` constructs the grid from a list of valid points.
Execution:
  Arrange: Prepare a list of valid points and the necessary parameters for `_on_watch_sub`. The list of points should be comprised of appropriate data types based on the function's expected inputs.
  Act: Invoke the function `_on_watch_sub`, passing the list of points and the necessary parameters.
  Assert: Check that the grid was successfully constructed and has extended with the correct number of rows corresponding to the points. Execution will not raise any exceptions.
Validation:
  Rationalize: This scenario verifies that the function correctly processes a list of valid points, ensuring the core functionality for constructing the metadata grid works as expected.

Scenario 2: Verify `_on_watch_sub` handles watch_id and watch_dis argument values
Details:
  TestName: test_watch_sub_watch_id_dis
  Description: Validate how the function `_on_watch_sub` uses watch_id and watch_dis to update metadata of the grid.
Execution:
  Arrange: Prepare necessary parameters for `_on_watch_sub`, including valid points and suitable watch_id and watch_dis values.
  Act: Invoke `_on_watch_sub`.
  Assert: Check that the grid's metadata contains matching items for watchId and watchDis.
Validation:
  Rationalize: This scenario ensures that `_on_watch_sub` is correctly utilizing watch_id and watch_dis to update grid's metadata items "watchId" and "watchDis" respectively.

Scenario 3: Verify `_on_watch_sub` handles lease argument values
Details:
  TestName: test_watch_sub_valid_lease
  Description: Validate how the function handles a valid lease argument.
Execution:
  Arrange: Prepare necessary parameters for `_on_watch_sub`, including valid points and a suitable lease value.
  Act: Invoke `_on_watch_sub`.
  Assert: Check that the grid's metadata contains a matching item for lease.
Validation:
  Rationalize: This scenario confirms that the function correctly uses the lease argument to update the grid's metadata item "lease".

Scenario 4: Test `_on_watch_sub` with callback function
Details:
  TestName: test_watch_sub_callback
  Description: Verify how `_on_watch_sub` handles a valid callback function.
Execution:
  Arrange: Construct necessary parameters for `_on_watch_sub`, including valid points and a valid callback function.
  Act: Invoke `_on_watch_sub`.
  Assert: Validate that the callback function is correctly utilized within `_post_grid` method during the process.
Validation:
  Rationalize: This use case ensures that `_on_watch_sub` properly utilizes the callback function when calling the `_post_grid` method, testing the behavior relevant to callbacks.
"""

# ********RoostGPT********
# Necessary imports
import pytest
import hszinc
from session import HaystackSession
from unittest.mock import MagicMock

class Test_HaystackSessionOnWatchSub:
    
    @pytest.mark.valid
    def test_watch_sub_valid_points(self):
        # Arrange
        session_obj = HaystackSession(...)
        points = ["point1", "point2", "point3"]
        watch_id = "sample_watch_id"
        watch_dis = "sample_watch_dis"
        lease = "sample_lease"
        callback = None

        # Act
        result = session_obj._on_watch_sub(points, watch_id, watch_dis, lease, callback)

        # Assert
        assert len(result.metadata) == 4  
        assert result.metadata["watchId"] == watch_id      
        assert result.metadata["watchDis"] == watch_dis      
        assert result.metadata["lease"] == lease      
        assert len(result) == len(points)    

    @pytest.mark.valid
    def test_watch_sub_watch_id_dis(self):
        # Arrange
        session_obj = HaystackSession(...)
        points = ["point1", "point2", "point3"]
        watch_id = "sample_watch_id"
        watch_dis = "sample_watch_dis"
        lease = None
        callback = None

        # Act
        result = session_obj._on_watch_sub(points, watch_id, watch_dis, lease, callback)

        # Assert
        assert result.metadata["watchId"] == watch_id
        assert result.metadata["watchDis"] == watch_dis

    @pytest.mark.valid
    def test_watch_sub_valid_lease(self):
        # Arrange
        session_obj = HaystackSession(...)
        points = ["point1", "point2", "point3"]
        watch_id = None
        watch_dis = None
        lease = "sample_lease"
        callback = None

        # Act
        result = session_obj._on_watch_sub(points, watch_id, watch_dis, lease, callback)

        # Assert
        assert result.metadata["lease"] == lease

    @pytest.mark.valid
    def test_watch_sub_callback(self):
        # Arrange
        session_obj = HaystackSession(...)
        points = ["point1", "point2", "point3"]
        watch_id = None
        watch_dis = None
        lease = None
        callback = MagicMock()

        # Act
        session_obj._post_grid = MagicMock()
        session_obj._on_watch_sub(points, watch_id, watch_dis, lease, callback)

        # Assert
        session_obj._post_grid.assert_called()
