# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonsetupTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonsetupTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonsetupTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=logout_f1ad123d15
ROOST_METHOD_SIG_HASH=logout_fc813b5064


Scenario 1: Successful Logout
Details:
  TestName: test_successful_logout
  Description: Test to verify if the successful logout leads to a status-code of 200 and a log message "You've been properly disconnected"
Execution:
  Arrange: Instantiate NiagaraHaystackSession object with correct uri, username, and password. Mock the _get method to return a response object with status code 200.
  Act: Call the logout method on NiagaraHaystackSession instance.
  Assert: Verify the log message matches "You've been properly disconnected".
Validation:
  It is vital to ensure the users are logged out successfully when the logout() method is called. A successful logout would return a status code of 200 and a corresponding log message.

Scenario 2: Logout with server error
Details:
  TestName: test_logout_with_server_error
  Description: Test to verify if server errors (status codes other than 200) lead to a warning message being logged "Failed to close nhaystack session" and "status_code={status_code}".
Execution:
  Arrange: Instantiate NiagaraHaystackSession object with correct uri, username, and password. Mock the _get method to return a response object with status code other than 200.
  Act: Call the logout method on NiagaraHaystackSession instance.
  Assert: Verify the log message to match "Failed to close nhaystack session" and "status_code={status_code}".
Validation:
  In the event of server errors during the logout process, the function should alert the user with appropriate error logs. This is crucial to understand any possible issues with the server.

Scenario 3: Logout when response has no status_code attribute
Details:
  TestName: test_logout_no_status_code
  Description: Verify if the logout function gracefully handles situations where there is no status_code attribute in the response.
Execution:
  Arrange: mock the _get method to return a response object without status_code attribute.
  Act: Call the logout method on NiagaraHaystackSession instance.
  Assert: Verify if the log message shows "Failed to close nhaystack session" and "status_code=-1".
Validation:
  This test is critical to understand how the function behaves when unexpected situations occur during logout, such as not receiving a status code in the response from the server. It tests the function's ability to handle exceptions gracefully.
"""

# ********RoostGPT********
import pytest
from unittest.mock import Mock
# Import the required classes from their correct packages
from pyhaystack.client.session import HaystackSession
from pyhaystack.client.niagara.NiagaraHaystackSession import NiagaraHaystackSession

class Test_NiagaraHaystackSessionLogout:

    @pytest.mark.positive
    def test_successful_logout(self):
        # Arrange
        session = NiagaraHaystackSession("http://testuri", "testuser", "testpass")
        session._get = Mock(return_value=Mock(status_code=200))

        # Mock the logger methods
        session._log.info = Mock()
        session._log.warning = Mock()

        # Act
        session.logout()

        # Assert
        session._log.info.assert_called_with("You've been properly disconnected")
        session._log.warning.assert_not_called()

    @pytest.mark.negative
    def test_logout_with_server_error(self):
        # Arrange
        session = NiagaraHaystackSession("http://testuri", "testuser", "testpass")
        session._get = Mock(return_value=Mock(status_code=404))

        # Mock the logger methods
        session._log.info = Mock()
        session._log.warning = Mock()

        # Act
        session.logout()

        # Assert
        session._log.warning.assert_any_call("Failed to close nhaystack session")
        session._log.warning.assert_any_call("status_code=404")
        session._log.info.assert_not_called()

    @pytest.mark.negative
    def test_logout_no_status_code(self):
        # Arrange
        session = NiagaraHaystackSession("http://testuri", "testuser", "testpass")
        session._get = Mock(return_value=Mock(side_effect=AttributeError("Mocked AttributeError")))

        # Mock the logger methods
        session._log.info = Mock()
        session._log.warning = Mock()

        # Act
        session.logout()

        # Assert
        session._log.warning.assert_any_call("Failed to close nhaystack session")
        session._log.warning.assert_any_call("status_code=-1")
        session._log.info.assert_not_called()
