# ********RoostGPT********
"""
Test generated by RoostGPT for test pyHaystackTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=watch_sub_ae15e3fc44
ROOST_METHOD_SIG_HASH=watch_sub_b9d53e6c9b


```
Scenario 1: Regular Call with only Points Parameter
Details:
  TestName: test_watchSub_regular_call
  Description: This test verifies that the function returns an expected grid when only points are passed.
Execution:
  Arrange: Initialize the points list with some valid point elements.
  Act: Invoke the function watch_sub with the points list.
  Assert: Check if the returned object is a grid and has the id column populated with the ids of the points passed.
Validation:
  This test validates that the function can correctly process points without requiring any other additional parameters.

Scenario 2: Regular Call with all Parameters
Details:
  TestName: test_watchSub_all_params
  Description: This test verifies that the function returns an expected grid when all parameters are passed.
Execution:
  Arrange: Initialize the points list with some valid point elements. Picker watch_id, watch_dis and lease.
  Act: Invoke the function watch_sub with all parameters.
  Assert: Check if the returned object is a grid, contains all metadata (watchId, watchDis, lease) and has id column populated with the ids of the points passed.
Validation:
  This validates that the function can correctly handle all parameters and populate them in the returned grid's metadata.

Scenario 3: Lease Parameter Type Validation
Details:
  TestName: test_watchSub_with_lease
  Description: This test verifies that the function handles lease parameter correctly, which should be of integer type.
Execution:
  Arrange: Initialize the points list with some valid point elements and lease with an integer value.
  Act: Invoke the function watch_sub with points and lease.
  Assert: Check whether the lease parameter is incorporated correctly into the grid's metadata as an integer.
Validation:
  This test ensures that the lease parameter, as an indication of when a watch should expire, is handled correctly and can be set as an integer.

Scenario 4: Invalid Points Parameter
Details:
  TestName: test_watchSub_invalid_points
  Description: This test verifies that the function handles invalid points correctly.
Execution:
  Arrange: Initialize points parameter with some invalid data types.
  Act: Invoke the function watch_sub with invalid points.
  Assert: Check whether the function raises an appropriate error.
Validation:
  This test ensures that the function properly validates the points parameter and throws an error when it can't recognize the inputs.
  
Scenario 5: Callback is Invoked
Details:
  TestName: test_watchSub_callback_invoked
  Description: This test verifies that if a callback function is provided as a parameter, it gets invoked correctly.
Execution:
  Arrange: Initialize the points list with some valid point elements and prepare a callback function.
  Act: Invoke the function watch_sub with points and callback function.
  Assert: Check whether the callback function is invoked.
Validation:
  This test confirms the asynchronous nature of the watch_sub function where it should be able to accept a callback and invoke it after processing.
```
"""

# ********RoostGPT********
import pytest
from session import HaystackSession
from http import sync
from hszinc import Grid, Ref
import logging
from entity.models.haystack import HaystackTaggingModel

# Prepare a class for testing
class Test_HaystackSessionWatchSub:
    def setup_class(self):
        # Initializing a session instance to be used in tests
        self.session = HaystackSession(
            uri="http://localhost:8000",
            api_dir="/",
            grid_format=hszinc.MODE_ZINC,
            http_client=sync.SyncHttpClient,
        )

    def test_watchSub_regular_call(self):
        points = ["point1", "point2"]
        result = self.session.watch_sub(points)
        assert isinstance(result, Grid)
        assert "id" in result.column
        for i, cell in enumerate(result):
            assert cell.get('id') in points

    def test_watchSub_all_params(self):
        points = ["point1", "point2"]
        watch_id = "test-watch-id"
        watch_dis = "test-watch-dis"
        lease = 900
        result = self.session.watch_sub(points, watch_id, watch_dis, lease)
        assert isinstance(result, Grid)
        assert "id" in result.column  
        assert result.metadata["watchId"] == watch_id
        assert result.metadata["watchDis"] == watch_dis
        assert result.metadata["lease"] == lease

    def test_watchSub_with_lease(self):
        points = ["point1", "point2"]
        lease = 900
        result = self.session.watch_sub(points, lease=lease)
        assert result.metadata["lease"] == lease
        assert isinstance(result.metadata["lease"], int)

    def test_watchSub_invalid_points(self):
        points = [100, 200, 300]
        with pytest.raises(ValueError):
            self.session.watch_sub(points)

    def test_watchSub_callback_invoked(self):
        points = ["point1", "point2"]
        invoked = {"called": False}
        def callback(*args, **kwargs):
            invoked["called"] = True
        self.session.watch_sub(points, callback=callback)
        assert invoked["called"]
